export const SET_COUNTRIES = 'SET_COUNTRIES';
export const SET_PLACE_DETAILS = 'SET_PLACE_DETAILS';
export const SET_MODAL_STATE = 'SET_MODAL_STATE';
export const SEARCH_QUERY = 'SEARCH_QUERY';
export const SEARCH_SUB_CATEGORY = 'SEARCH_SUB_CATEGORY';
